name: reflete_prime
description: O Ecossistema Digital da Reflete Engenharia.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  url_launcher: ^6.2.0
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.65.0  # Para grÃ¡ficos financeiros
  intl: ^0.19.0      # Para datas
  timelines: ^0.1.0  # Para a linha do tempo da obra

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
